# Nombre del Pipeline
name: Java Pipeline

# Gatillo del Pipeline (cuándo se ejecutará el pipeline)
trigger:
- main

# Configuración del Agente (el tipo de máquina virtual que se utilizará)
pool:
  vmImage: ubuntu-latest

# Pasos del Pipeline
steps:
- task: Gradle@2
  displayName: 'Build Java project and run tests with Gradle'
  inputs:
    workingDirectory: '' # Directorio de trabajo del proyecto
    gradleWrapperFile: 'gradlew' # Nombre del archivo wrapper de Gradle
    gradleOptions: '-Xmx3072m' # Opciones de Gradle
    javaHomeOption: 'JDKVersion' # Opción del JDK
    jdkVersionOption: '1.8' # Versión de JDK
    jdkArchitectureOption: 'x64' # Arquitectura de JDK
    publishJUnitResults: true # Publicar resultados de JUnit
    testResultsFiles: '**/TEST-*.xml' # Patrón de archivos de resultados de pruebas
    tasks: 'build' # Tareas a ejecutar (en este caso, solo construir el proyecto)
